steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'slackBookmark', '--runtime=nodejs8', '--trigger-http', '--region=asia-northeast1']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'slackBookmarkPickRandomly', '--runtime=nodejs8', '--trigger-http', '--region=asia-northeast1']
